### PR TITLE
Create CheckArmstrongNumber.py

### PR DESCRIPTION
**Pull request by vijoyaliyan**
Program to check whether the given number is Armstrong or not

### CODE REVIEW

**Comment by sonumahajan** [comment]
Add this in python file

**Comment by vijoyaliyan** [comment]
Sir, I have created the file inside Python folder. But I couldn't find any move folder inside the Python folder.
Kkndly help me.

**Comment by vijoyaliyan** [comment]
Okay sir

**Comment by sonumahajan** [comment]
Follow me on github

**Pull request merged**
