### PR TITLE
Create Find Minimum in Rotated Sorted Array.cpp

### PR DESCRIPTION
**Pull request by Srishti2128**
This code allows to find the minimum in sorted rotated array nums of unique elements.

### CODE REVIEW

**Comment by sonumahajan** [comment]
You can follow me on GitHub

**Comment by Srishti2128** [comment]
@sonumahajan Kindly add hacktoberfest-accepted label to the Pull request. Being an admin/maintainer, only you can do that and it's SOP for adding the label as per Hacktoberfest website.

**Comment by sonumahajan** [comment]
Done, sorry i had forgot to add that label.

**Comment by Srishti2128** [comment]
No issues. Thanks for adding it now !!

**Pull request merged**
